import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "./Footer";
import Navbar from "./NavBar";
import NewTodo from "./NewTodo";

const MainContainer = ({
  children,
  setData,
  data,
  todoStatus,
  setTodoStatus,
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.wrapper}>
          <NewTodo
            setData={setData}
            data={data}
            todoStatus={todoStatus}
            setTodoStatus={setTodoStatus}
          />
          {children}
        </div>
        <Navbar data={data} />
      </main>
      <Footer />
    </div>
  );
};

export default MainContainer;
