import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapper}>
          <form className={styles.form}>
            <div className={styles.inputWrapper}>
              <button className={styles.completeAll}></button>
              <input
                type="text"
                className={styles.input}
                placeholder="What needs to be done?"
              />
            </div>
            <ul className={styles.todosList}>
              <li className={styles.todosItem}>
                <span className={styles.status}></span>
                <div className={styles.taskWrapper}>
                  <input className={styles.task} type="text" />
                  <button className={styles.remove}></button>
                </div>
              </li>
              <li className={styles.todosItem}>
                <span className={styles.status}></span>
                <div className={styles.taskWrapper}>
                  <input className={styles.task} type="text" />
                  <button className={styles.remove}></button>
                </div>
              </li>
              <li className={styles.todosItem}>
                <span className={styles.status}></span>
                <div className={styles.taskWrapper}>
                  <input className={styles.task} type="text" />
                  <button className={styles.remove}></button>
                </div>
              </li>
            </ul>
          </form>
        </div>
        <Navbar />
      </main>

      <footer className={styles.footer}>
        <p>Powered by woofmgn</p>
      </footer>
    </div>
  );
}
