import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import NewTodo from "../components/NewTodo";
import TodosList from "../components/TodosList";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.wrapper}>
          <NewTodo />
          <TodosList />
        </div>
        <Navbar />
      </main>
      <Footer />
    </div>
  );
}
